### ISSUE TITLE
significant difference between Phatyp and BACPHLIP

### ISSUE THREAD

**Issue by ShailNair** [KennthShang/PhaTYP#2]
Hello, thank you for the excellent tool. I used Phatyp to compare my metagenomic data with [BACPHLIP](https://peerj.com/articles/11396/). To be more stringent I used the following criteria:

1) [CheckV](https://www.nature.com/articles/s41587-020-00774-7) was performed on the tested viral contigs to ensure that they were complete and free of contamination.
2) Phatyp and BACPHLIP were run using default parameters.
3) Only contigs from both predictions with a probability score of >= 0.95 were taken into account for the final analysis.

Here, are the results:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

classifier | No. of temperate | No. of virulent | contrasting   predictions with respect to BACPHLIP | Not assigned
-- | -- | -- | -- | --
PhaTYP | 92 | 181 | 157 as virulent, 11   as temperate | 59
BACPHLIP | 284 | 48 |   | 0

</body>

</html>

It seems like there is a significant difference between the output of the two classifiers.

**Comment by KennthShang** [comment]
Hi, 

Thanks for using our tool. 

It seems the difference is quite large in your provided data. I am also confused about this because, in previous experiments, the gap between the two classifiers on complete genomes (If you refer to the CheckV can guarantee your contigs are complete genomes) is not larger than 5%.

However, if you are asking why this happen, I am afraid that I cannot give you an exact answer since I do not know the ground truth of your phages. What I can tell is, based on our benchmark dataset,  PhaTYP has better robustness than BACPHLIP, especially on assembled contigs.  Another piece of information that may help you is the database used in BACPHLIP are from three years ago, which might lead to some problems.

Back to your data. Again, since we do not know the ground truth, it is hard to tell which classifier makes the right prediction, and I do not like to draw an uncertain conclusion when comparing my tools and other people's work. Although the two classifiers are both learning protein homology features, the detailed structures and the database are different. So, it might be reasonable if there exist large differences in some special cases.

Best,
Jiayu

**Comment by ShailNair** [comment]
Yes, I agree that the results could vary depending on the type and diversity of the dataset. Most certainly, as more users will utilize the PhaTYP tool, will have a clearer insight.

Thank you.
